version: "3"
services:
  app:
    build: .
    container_name: dronepilot-app
    ports:
      - "3000:3000"  
    volumes:
      - .:/usr/src/app  
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/dronepilot  
    depends_on:
      - mongo 

  mongo:
    image: mongo:latest  
    container_name: dronepilot-mongo
    ports:
      - "27017:27017"  
    volumes:
      - mongo-data:/data/db  

volumes:
  mongo-data:
